### ISSUE TITLE
The Toast will not be shown in Action Center

### ISSUE THREAD

**Issue by Andis59** [psantosl/ConsoleToast#2]
First, a BIG thank you for creating this! 

I have a small problem though. I'm using your code to show a notification when a program is done and what it has done. It will show the toast as expected, but since I'm not always around when the toast is shown I would expect that it was "saved" in _Action Center_, like all the others.

It's not!

Any idea on what could be wrong?
I'm using _ShowTextToast_ if that matters...

**Comment by Andis59** [comment]
I found out why!

> You must set a registry key for each AppID whose notifications you would like to persist in the Action Center.
> 
> For example, if you want your AppID notifications to persist, add the key: HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\AppId with a DWORD named ShowInActionCenter with value 1.
> 
> 

The above quote is from the accepted answer here:
[https://stackoverflow.com/questions/31772192/toastnotifications-sent-from-powershell-disappear-from-action-center](https://stackoverflow.com/questions/31772192/toastnotifications-sent-from-powershell-disappear-from-action-center?noredirect=1&lq=1)

**Comment by psantosl** [comment]
Wow! Thanks! I was clueless :-)
